//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.SupermarketOffers
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MercadonaDTO", Namespace="http://schemas.datacontract.org/2004/07/WS.Unit06.User.Application.Model")]
    public partial class MercadonaDTO : object
    {
        
        private string imageUrlField;
        
        private string previousPriceField;
        
        private string priceField;
        
        private string titleField;
        
        private string urlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imageUrl
        {
            get
            {
                return this.imageUrlField;
            }
            set
            {
                this.imageUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string previousPrice
        {
            get
            {
                return this.previousPriceField;
            }
            set
            {
                this.previousPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarrefourDTO", Namespace="http://schemas.datacontract.org/2004/07/WS.Unit06.User.Application.Model")]
    public partial class CarrefourDTO : object
    {
        
        private string descriptionField;
        
        private string imageUrlField;
        
        private string priceField;
        
        private string titleField;
        
        private string unitPriceField;
        
        private string urlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string imageUrl
        {
            get
            {
                return this.imageUrlField;
            }
            set
            {
                this.imageUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string unitPrice
        {
            get
            {
                return this.unitPriceField;
            }
            set
            {
                this.unitPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.unit06.user/auth/", ConfigurationName="WSClient.SupermarketOffers.ISupermarketOffersServices")]
    public interface ISupermarketOffersServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit06.user/auth/ISupermarketOffersServices/getAllMercadonaOffers", ReplyAction="http://ws.unit06.user/auth/ISupermarketOffersServices/getAllMercadonaOffersRespon" +
            "se")]
        WSClient.SupermarketOffers.MercadonaDTO[] getAllMercadonaOffers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit06.user/auth/ISupermarketOffersServices/getAllMercadonaOffers", ReplyAction="http://ws.unit06.user/auth/ISupermarketOffersServices/getAllMercadonaOffersRespon" +
            "se")]
        System.Threading.Tasks.Task<WSClient.SupermarketOffers.MercadonaDTO[]> getAllMercadonaOffersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit06.user/auth/ISupermarketOffersServices/getAllCarrefourOffers", ReplyAction="http://ws.unit06.user/auth/ISupermarketOffersServices/getAllCarrefourOffersRespon" +
            "se")]
        WSClient.SupermarketOffers.CarrefourDTO[] getAllCarrefourOffers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws.unit06.user/auth/ISupermarketOffersServices/getAllCarrefourOffers", ReplyAction="http://ws.unit06.user/auth/ISupermarketOffersServices/getAllCarrefourOffersRespon" +
            "se")]
        System.Threading.Tasks.Task<WSClient.SupermarketOffers.CarrefourDTO[]> getAllCarrefourOffersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ISupermarketOffersServicesChannel : WSClient.SupermarketOffers.ISupermarketOffersServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class SupermarketOffersServicesClient : System.ServiceModel.ClientBase<WSClient.SupermarketOffers.ISupermarketOffersServices>, WSClient.SupermarketOffers.ISupermarketOffersServices
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SupermarketOffersServicesClient() : 
                base(SupermarketOffersServicesClient.GetDefaultBinding(), SupermarketOffersServicesClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISupermarketOffersServices.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SupermarketOffersServicesClient(EndpointConfiguration endpointConfiguration) : 
                base(SupermarketOffersServicesClient.GetBindingForEndpoint(endpointConfiguration), SupermarketOffersServicesClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SupermarketOffersServicesClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SupermarketOffersServicesClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SupermarketOffersServicesClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SupermarketOffersServicesClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SupermarketOffersServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WSClient.SupermarketOffers.MercadonaDTO[] getAllMercadonaOffers()
        {
            return base.Channel.getAllMercadonaOffers();
        }
        
        public System.Threading.Tasks.Task<WSClient.SupermarketOffers.MercadonaDTO[]> getAllMercadonaOffersAsync()
        {
            return base.Channel.getAllMercadonaOffersAsync();
        }
        
        public WSClient.SupermarketOffers.CarrefourDTO[] getAllCarrefourOffers()
        {
            return base.Channel.getAllCarrefourOffers();
        }
        
        public System.Threading.Tasks.Task<WSClient.SupermarketOffers.CarrefourDTO[]> getAllCarrefourOffersAsync()
        {
            return base.Channel.getAllCarrefourOffersAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISupermarketOffersServices))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISupermarketOffersServices))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9091/SupermarketOffertServices.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SupermarketOffersServicesClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISupermarketOffersServices);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SupermarketOffersServicesClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISupermarketOffersServices);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISupermarketOffersServices,
        }
    }
}
